### ISSUE TITLE
extension color override

### ISSUE THREAD

**Issue by DavidRR-F** [michaelbrusegard/tabline.wez#24]
Great plugin! Is there a way to override the colors of the predefined extensions? Mine seems to revert back to the default theme and ignore the overrides I have configured 

![image](https://github.com/user-attachments/assets/6f04d88c-d53d-4406-afc6-28c7ea129a9a)

![image](https://github.com/user-attachments/assets/ed00d7b1-6071-46d0-983f-bc7808f87259)

**Comment by michaelbrusegard** [comment]
Hey, the colors in the extensions cannot be overwritten. In the screenshots you are defining colors for a new custom keytable (mode).

If you want custom colors for the extension you need to create your own extension with your own colors of choice. I can probably implement a way to do it differently in the future though.

For now just copy the extension from here and pass in your own with different colors:
https://github.com/michaelbrusegard/tabline.wez/blob/main/plugin/tabline/extensions/quick_domains.lua

**Comment by michaelbrusegard** [comment]
I will mark this as solved, if you want and feel like it would be nice you can create a new issue with a feature request for an API to modifying the built in extensions the same way you can modify components. I would like to find out how much people want that before I implement it or if it is enough to be able to create your own extensions since it will basicly do the same just a matter of how
