### ISSUE TITLE
Feature Request: Separate Color Configuration for Section X-Z

### ISSUE THREAD

**Issue by 0xJWLabs** [michaelbrusegard/tabline.wez#28]
Hi,

I’ve noticed that when trying to customize the colors for section z in the tabline, it seems tied to section a, which makes it difficult to style each section individually. I’m specifically looking for a way to modify the colors of section z independently, without affecting section a’s styling.

For example, this doesn’t seem to work as expected:

```lua
normal_mode = {
   z = { fg = colors.text, bg = colors.crust },
}
```

It would be really helpful if there were a way to apply different colors to section z without having to change other sections, allowing more flexibility with the tabline design.

Thanks for considering this!

**Comment by michaelbrusegard** [comment]
After reading up on how lualine is doing this [here](https://github.com/nvim-lualine/lualine.nvim/wiki/Writing-a-theme) I see that they support setting x, y and z but default back to a, b and c. Because of that I think this should be added. it is a little sizeable change so I can not promise when I will have time to implement it

**Comment by 0xJWLabs** [comment]
@michaelbrusegard Alright thanks! Can't wait for it!
